10Homework/Shop_Phone_MVC/Shop_Phone_MVC/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DBInterfaces;
using Microsoft.AspNetCore.Mvc;
using Shop_Phone_MVC.Filters;
using Shop_Phone_MVC.Models;

namespace Shop_Phone_MVC.Controllers
{
    [CustomerExeptionFilter]
    //для отображения страницы корзины
    public class BasketController : Controller
    {
        private readonly IServiceDBBasket dbB;
        BasketViewModel model = new BasketViewModel();
        public BasketController(IServiceDBBasket ado_)
        {
            dbB = ado_;
        }
        public IActionResult Basket()
        {
            LoadPhone();
            if (model.phones.Count==0)
            { ViewBag.Message = "У вас нет товаров"; }
            return View(model);
        }
       
        public  void LoadPhone()
        {
           model.phones= dbB.SelectPhoneByCustomer(User.Identity.Name).Result;
        }
        [HttpPost]
        public IActionResult Basket(int id)
        {
            dbB.DeleteFromBasket(id, User.Identity.Name).Wait();
            LoadPhone();
            return View(model);
        }
    }
}

10Homework/Shop_Phone_MVC/Shop_Phone_MVC/Controllers/PhoneController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using DBInterfaces;
using LibrarySetOfClases;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Shop_Phone_MVC.Filters;
using Shop_Phone_MVC.Models;

namespace Shop_Phone_MVC.Controllers
{
    [CustomerExeptionFilter]
    //для отображения главной страницы покупки телефонов
    public class PhoneController : Controller
    {
        private readonly IServiceDBPhone dbP;
        private readonly IServiceDBBasket dbB;
        private readonly IServiceDBCustomer dbC;
        private List<ClassPhone> phones = new List<ClassPhone>();
        private List<ClassPhone> basket_phone = new List<ClassPhone>();
        private List<Customer> customers = new List<Customer>();
        private List<Basket> users_basket = new List<Basket>();
        private PhonesViewModel phoneViewModel = new PhonesViewModel();
        private List<PhoneViewModel> phoneViews = new List<PhoneViewModel>();
        public PhoneController(IServiceDBPhone dbP, IServiceDBBasket dbB, IServiceDBCustomer dbC)
        {
            this.dbP = dbP;
            this.dbC = dbC;
            this.dbB = dbB;
            //проверка отображения error-страницы
            // throw new Exception();
        }
        [HttpGet]
        public IActionResult Phone()
        {
            phoneViews=Load_Data();
            phoneViewModel = new PhonesViewModel { NameUser = User.Identity.Name, Message = "Hello", phonesview = phoneViews };
            return View(phoneViewModel);
        }
        public List<PhoneViewModel> Load_Data()
        {
            List<PhoneViewModel> phoneViews = new List<PhoneViewModel>();
            phones = dbP.SelectPhone().Result;
            foreach(ClassPhone cl in phones)
            {
                PhoneViewModel p = new PhoneViewModel();
                p.ID = cl.IDPhone;
                p.Marka = cl.Marka;
                p.Memory = cl.Memory;
                p.Model = cl.Model;
                p.Price = cl.Price;
                p.Sourse = "~/images/phone.jpg";
                p.Description = cl.Desc;
                p.Count = cl.Count;
                p.Camera = cl.Camera;
                p.Battery = p.Battery;
                phoneViews.Add(p);
            }
            return phoneViews; 
        }
       
        [HttpPost]
        public IActionResult Phone(int id)
        {
            phoneViews=Load_Data();
            if (User.Identity.Name ==null)
            {
                phoneViewModel.Message = "You need to registration";
                phoneViewModel = new PhonesViewModel { NameUser = User.Identity.Name, Message = "Sorry.You can`t buy phones.", phonesview = phoneViews };
                return View(phoneViewModel);
                
            }
            else
            {
                for (int i = 0; i < phones.Count; i++)
                {
                    if (phones[i].IDPhone == id)
                    {
                        AddProductToBasket(id);
                        phoneViewModel = new PhonesViewModel { NameUser ="", Message = "Phone is aded to basket", phonesview = phoneViews };
                        break;
                    }
                }
                return View(phoneViewModel);
            }
            
        }
        
        public void AddProductToBasket(int id_phone)
        {
            bool f = true;
            customers= dbC.SelectCustomer().Result;
            users_basket = dbB.SelectUsersBasket().Result;
            foreach (Customer cl in customers)
            {if(cl.Login.Trim()==User.Identity.Name)
                { foreach(Basket b in users_basket)
                    {
                        if(b.Login_U.Trim()==User.Identity.Name)
                        {
                            dbB.InsertInBasketPhone( cl.IDcustomer, id_phone).Wait();f = false; break;
                        }
                    }
                    if (f == true)
                    {
                        dbB.InsertInBasketID(cl.IDcustomer).Wait();
                        dbB.InsertInBasketPhone( cl.IDcustomer, id_phone).Wait(); break;
                    }
                }
            }
            
        }
       
    }
}

10Homework/Shop_Phone_MVC/Shop_Phone_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shop_Phone_MVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" style="background-color:darkgreen;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Phone" asp-action="Phone"style="color:white" class="navbar-brand">MobiCat</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Phone" style="color:white"  asp-action="Phone">Телефоны</a></li>
                    <li><a asp-area="" asp-controller="Account" style="color:white" asp-action="Entrance">Вход/Регестрация</a></li>
                    <li><a asp-area="" asp-controller="Basket" style="color:white"  asp-action="Basket">Корзина</a></li>
                    <li><a asp-area="" asp-controller="Home" style="color:white" asp-action="About">О компании</a></li>
                    <li><a asp-area="" asp-controller="Home" style="color:white"  asp-action="Contact">Контакты</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Shop_Phone_MVC</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>